inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'build/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Max: 50
  ExcludedMethods: ['describe', 'context']

Metrics/ModuleLength:
  Exclude:
    - !ruby/regexp /^test\//
